name: Build and Release

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\src\DeserializerApp.sln

  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x86

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: CHCP 437 && msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}} /bl

    - uses: actions/upload-artifact@v2
      with:
        name: Deserializer(32-bit)
        path: |
          src\Release\x86

  test:
    runs-on: self-hosted
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: Deserializer(32-bit)
        path: .\Artifacts

    - name: Unzip Artifact
      shell: powershell
      run: Expand-Archive -Path .\Artifacts\Deserializer(32-bit).zip -Destination .\Artifacts\Deserializer(32-bit) -Force

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Run Tests
      shell: cmd
      run: CHCP 437 && vstest.console.exe .\Artifacts\Deserializer(32-bit)\DeserializerTests.elb

  release:
    runs-on: self-hosted
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: Deserializer(32-bit)
        path: .\Artifacts

    - name: Unzip Artifact
      shell: powershell
      run: Expand-Archive -Path .\Artifacts\Deserializer(32-bit).zip -Destination .\Artifacts\Deserializer(32-bit) -Force

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        artifacts: Artifacts\Deserializer(32-bit)\*.elb,Artifacts\Deserializer(32-bit)\*.dbr
        body: New Deserializer Release
        name: Deserializer(32-bit)