name: Build and Release

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\src\DeserializerApp.sln

  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x86

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: CHCP 437 && msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}} /bl

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Run Tests
      shell: cmd
      run: CHCP 437 && vstest.console.exe .\src\Release\x86\DeserializerTests.elb

    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: Deserializer(32-bit)
        path: |
          src\Release\x86

    - name: Create Release Package
      shell: powershell
      run: Copy-Item -Path ".\src\Release\x86\*" -Destination ".\Deserializer(32-bit)" -Exclude "*.dbp","SynergyTraditionalUnitTest.TestAdapter.dll"

    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
          GHR_COMPRESS: zip
          GHR_PATH: .\Deserializer(32-bit)
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}