name: Build and Release

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\src\DeserializerApp.sln

  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x86

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: CHCP 437 && msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}} /bl

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Run Tests
      shell: cmd
      run: CHCP 437 && vstest.console.exe .\Artifacts\Deserializer(32-bit)\DeserializerTests.elb

    - name: Upload built files
    - uses: actions/upload-artifact@v2
      with:
        name: Deserializer(32-bit)
        path: |
          src\Release\x86

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        artifacts: .\src\Release\x86\*.elb,.\src\Release\x86\*.dbr
        body: New Deserializer Release
        name: Deserializer(32-bit)